import { createWriteStream } from 'fs';
import { resolve } from 'path';

// For Next.js, we'll generate PDF using a simple approach
// Make sure to install: npm install pdfkit
export class PdfService {
  static async generateAlertsPdf(
    vehicleNumber: string,
    date: string,
    records: any[],
  ): Promise<Buffer> {
    // Dynamically import PDFKit (ESM compatibility)
    const PDFDocument = (await import('pdfkit')).default;

    return new Promise((resolve, reject) => {
      const chunks: any[] = [];
      const doc = new PDFDocument({ margin: 50, size: 'A4' });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      // Header
      this.generateHeader(doc);

      // Title
      doc
        .fillColor('#1e5bd8')
        .fontSize(20)
        .text('Alert Records Report', 50, 100)
        .fontSize(10)
        .fillColor('#64748b')
        .text(`Vehicle: ${vehicleNumber}`, 50, 125)
        .text(`Date: ${date}`, 50, 140)
        .moveDown();

      // Table Header
      const tableTop = 170;
      doc
        .fillColor('#334155')
        .fontSize(10)
        .text('S.No', 50, tableTop, { width: 30 })
        .text('Time', 90, tableTop, { width: 60 })
        .text('Alert Type', 160, tableTop, { width: 100 })
        .text('Speed', 270, tableTop, { width: 50 })
        .text('Description', 330, tableTop);

      this.generateHr(doc, tableTop + 20);

      // Table Records
      let currentY = tableTop + 30;
      records.forEach((record) => {
        if (currentY > 700) {
          doc.addPage();
          currentY = 50;
        }

        doc
          .fillColor('#475569')
          .fontSize(9)
          .text(record.sNo.toString(), 50, currentY, { width: 30 })
          .text(new Date(record.time).toLocaleTimeString(), 90, currentY, { width: 60 })
          .text(record.alertType, 160, currentY, { width: 100 })
          .text(`${record.speed} km/h`, 270, currentY, { width: 50 })
          .text(record.description, 330, currentY);

        currentY += 25;
        this.generateHr(doc, currentY - 5);
      });

      // Footer
      const pageCount = (doc as any).bufferedPageCount;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc
          .fontSize(8)
          .fillColor('#94a3b8')
          .text(
            `Generated by Masstrans Alerts System on ${new Date().toLocaleString()}`,
            50,
            doc.page.height - 50,
            { align: 'center', width: doc.page.width - 100 }
          );
      }

      doc.end();
    });
  }

  private static generateHeader(doc: any) {
    doc
      .fillColor('#000000')
      .fontSize(10)
      .text('MASSTRANS ALERTS', 50, 45, { align: 'right' })
      .moveDown();
  }

  private static generateHr(doc: any, y: number) {
    doc
      .strokeColor('#e2e8f0')
      .lineWidth(1)
      .moveTo(50, y)
      .lineTo(550, y)
      .stroke();
  }
}
